### ISSUE TITLE
OrderGuard 2.0 — Intelligence Layer Extensions

### ISSUE THREAD

**Issue by dc-deal** [dc-deal/FiniexTestingIDE#276]
The OrderGuard (implemented in #267) currently enforces two rules: SHORT+SPOT blocking and rejection cooldown. Both are reactive — they prevent known-bad orders from reaching the executor.

This issue tracks a second tier of guards that add **proactive intelligence**: blocking orders that are technically valid but operationally dangerous. These extensions share the same `validate()` interface (`OpenOrderRequest → Optional[OrderResult]`) and require no architectural changes to the guard itself.

The extensions split into two tiers based on data requirements:

### Tier A — Self-Contained (no new dependencies)

These checks use only the `OpenOrderRequest` and internal guard state. They fit directly into `OrderGuard.validate()` today.

**A1. Rate Limiting**

Hard cap on orders per time window, independent of rejection state. Prevents API rate limit violations at brokers (e.g. Kraken enforces request limits per minute). The cooldown only activates *after* rejections — rate limiting activates *before* any problem occurs.

```
validate():
    if orders_in_window[direction] >= max_orders_per_window:
        → RATE_LIMITED
```

Config: `max_orders_per_window: int`, `window_seconds: float`

**A2. Position Limit Guard**

**Hard ceiling** on simultaneous open positions — a safety net the algo should never normally hit.

Today every decision logic implements position checks individually (`if len(positions) >= max: return None`). These per-tick checks are **intentional strategy decisions** that happen during normal operation — they are NOT guard candidates. Moving them to the guard would flood `order_history` with rejections on every tick, destroying forensic value.

The Position Limit Guard is a **structural safety net**: it catches bugs where a decision logic accidentally tries to pyramid beyond its intended limit. The algo should never reach this ceiling during correct operation.

```
validate():
    if open_position_count >= max_open_positions:
        → MAX_POSITIONS_REACHED
```

Example: AggressiveTrend declares `max_open_positions=1`. The strategy's own `if len(open_positions) > 0: return None` handles the normal case silently. The guard catches the bug where a race condition or logic error sends a second order anyway.

**Heuristic:** Frequent per-tick decisions → strategy-local (`return None`). Rare structural failures → guard (`→ MAX_POSITIONS_REACHED`).

Requires: portfolio query in guard (today the guard is portfolio-blind). Options:
- Inject `executor.get_open_positions()` callable at construction
- Pass position count as argument to `validate()`
- Query via callback (same pattern as `_notify_outcome`)

Config: `max_open_positions: int` (0 = disabled)

**A3. Max Exposure / Lot Cap**

Prevents unbounded pyramiding — cap on total lots in one direction.

```
validate():
    if total_lots[direction] + request.lots > max_lots_per_direction:
        → MAX_EXPOSURE_REACHED
```

Requires: same portfolio access as A2 (directional lot sum).

Config: `max_lots_per_direction: float` (0 = disabled)

### Tier B — Needs External Data Injection

These checks need market data beyond the `OpenOrderRequest`. They require extending the guard's interface — either by injecting data at construction or by passing tick context to `validate()`.

**B1. Market Hours Guard**

Block orders outside known trading hours. `MARKET_CLOSED` already exists as a `RejectionReason`. Saves a broker roundtrip when the market is closed.

```
validate():
    if not market_schedule.is_open(symbol, now):
        → MARKET_CLOSED
```

Requires: market schedule data (per symbol/broker). Could be static config or adapter query.

## Design Constraint

The guard's strength is its simplicity: `validate(request) → Optional[OrderResult]`. Tier A extensions preserve this. B1 may require `validate(request, context=...)` — evaluate carefully whether schedule data can be injected at construction instead.

A2 and A3 sit at the boundary — they need position data but not tick data. A lightweight callback or count injection may be enough without changing `validate()` signature.

## Scope — What the OrderGuard Is (and Is Not)

The OrderGuard enforces exactly two categories of rules:

1. **Broker would reject** — the order is structurally invalid (SHORT on SPOT, rate limit exceeded, market closed). The guard saves a roundtrip.
2. **Algo bug** — the order passed strategy logic but shouldn't have (position limit exceeded due to race condition, rejection spam due to logic error). The guard is a safety net the algo should never normally trigger.

**Not in scope:** Market quality decisions (spread width, volatility, liquidity depth). These are not rejections — brokers fill them happily, just at bad prices. Market quality belongs in a future **MarketConditionMonitor** layer (separate concern, separate issue) or in the strategy's `compute()` logic.

**Heuristic:** "Would the broker reject this, or does it indicate an algo bug?" → OrderGuard. "Is the market in a state where we'd prefer not to trade?" → not OrderGuard.

## New RejectionReasons Required

```python
RATE_LIMITED = 'rate_limited'
MAX_POSITIONS_REACHED = 'max_positions_reached'
MAX_EXPOSURE_REACHED = 'max_exposure_reached'
# MARKET_CLOSED already exists
```

## Implementation Priority

| Extension | Value | Complexity | Suggested Order |
|-----------|-------|------------|-----------------|
| A1. Rate Limiting | High (API ban prevention) | Low | First |
| A2. Position Limit | High (universal safety) | Medium (needs portfolio access) | Second |
| A3. Max Exposure | Medium (pyramiding protection) | Medium (same as A2) | With A2 |
| B1. Market Hours | Medium (saves roundtrips) | Medium (schedule data source) | Third |

## Related

- **#267** — OrderGuard V1 (SHORT+SPOT + rejection cooldown) — ✅ Done
- **#270** — Safety Circuit Breaker (account-level, independent layer)
- **#151** — Reconciliation Layer (async outcome infrastructure reusable here)

---

**Requires: tests for each new guard rule (unit + scenario). Update `docs/architecture/order_guard_architecture.md` with new rules. Review `OrderGuardConfig` extension (new fields per rule).**
